/*
 * Random visitor name generator. Echoes the tone of the Figma cards:
 * "flower dreamer", "lovely philosophist", "...".
 * Aim for pretty-whimsical, not random: storybook, floral, cozy, celestial.
 */

const adjectives = [
  "flower",
  "lovely",
  "quiet",
  "sunlit",
  "midnight",
  "tender",
  "amber",
  "wandering",
  "linen",
  "paper",
  "salt",
  "honey",
  "velvet",
  "morning",
  "rainy",
  "violet",
  "small",
  "soft",
  "cozy",
  "plum",
  "peach",
  "maple",
  "ginger",
  "cinnamon",
  "clover",
  "dewy",
  "mossy",
  "starlit",
  "moonlit",
  "drowsy",
  "hazel",
  "mulberry",
  "sleepy",
  "pearl",
  "cloudy",
  "misty",
  "lavender",
  "saffron",
  "almond",
  "chestnut",
  "fern",
  "lemon",
  "apricot",
  "golden",
  "silver",
  "rosy",
  "little",
  "merry",
  "hushed",
  "wistful",
  "opal",
  "rosewater",
  "willow",
  "juniper",
  "marigold",
  "buttery",
  "woolen",
  "candlelit",
  "drifting",
  "parchment",
  "coral",
  "frosted",
  "blushing",
  "twilight",
  "cedar",
  "sage",
  "dusky",
  "silken",
  "thistle",
  "porcelain",
  "meadow",
  "heather",
  "birch",
  "ivy",
  "nutmeg",
  "cardamom",
  "cocoa",
  "vanilla",
  "primrose",
  "jasmine",
  "indigo",
  "scarlet",
  "dappled",
];

const nouns = [
  "dreamer",
  "philosophist",
  "wanderer",
  "letter",
  "atlas",
  "cartographer",
  "ember",
  "harbor",
  "draft",
  "songbird",
  "tide",
  "thinker",
  "sketcher",
  "almanac",
  "compass",
  "lantern",
  "weaver",
  "bookmark",
  "figure",
  "starling",
  "poet",
  "reverie",
  "lullaby",
  "keeper",
  "goblin",
  "fairy",
  "pixie",
  "owlet",
  "nightingale",
  "sparrow",
  "swallow",
  "firefly",
  "dragonfly",
  "botanist",
  "daydreamer",
  "stargazer",
  "moonchild",
  "storyteller",
  "locket",
  "orchid",
  "peony",
  "grove",
  "queen",
  "scribe",
  "moth",
  "petal",
  "acorn",
  "thimble",
  "candle",
  "quill",
  "teacup",
  "trinket",
  "riddle",
  "fable",
  "mirage",
  "crescent",
  "meadowlark",
  "finch",
  "wren",
  "heron",
  "lamplighter",
  "wayfarer",
  "inkwell",
];

function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Pairs that are individually innocent words but collide into loaded
// real-world references. Keep tiny; reroll on hit.
const blockedPairs = new Set<string>([
  "pearl harbor",
]);

export function generateVisitorName(): string {
  for (let i = 0; i < 8; i++) {
    const name = `${pick(adjectives)} ${pick(nouns)}`;
    if (!blockedPairs.has(name)) return name;
  }
  // Exhausted retries (absurdly unlikely): fall back to a safe default.
  return "flower dreamer";
}
